package com.epam.facultative.model.dao.impl_sql;

import com.epam.facultative.model.dao.CourseDao;
import com.epam.facultative.model.entities.*;
import com.epam.facultative.model.exception.DAOException;
import com.epam.facultative.model.exception.ValidateException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import javax.sql.DataSource;
import java.sql.*;
import java.sql.Date;
import java.util.*;

import static com.epam.facultative.model.dao.impl_sql.сonstants.SQLRequestConstants.*;
import static com.epam.facultative.model.dao.impl_sql.сonstants.FieldsConstants.*;
import static com.epam.facultative.model.exception.ConstantsValidateMessage.TITLE_NOT_UNIQUE_MESSAGE;

/**
 * Course DAO class for My SQL database. Matches table "course" in database.
 *
 * @author Oleksandr Pacnhenko
 * @version 1.0
 */
@Slf4j
@RequiredArgsConstructor
public class MySqlCourseDao implements CourseDao {
    private final DataSource dataSource;

    /**
     * Obtains instance of Course from database by parameter
     *
     * @param param -  parameter value
     * @return Optional.ofNullable - course is null if the course is not found.
     * @throws DAOException is wrapper for SQLException
     */
    @Override
    public Optional<Course> get(String param) throws DAOException {
        Course course = null;
        try (Connection con = dataSource.getConnection();
             PreparedStatement stmt = con.prepareStatement(String.format(SELECT_COURSE, param))) {
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                course = mapRowCourse(rs);
            }
        } catch (SQLException e) {
            log.error(String.format("Couldn't get the Course. Cause: %s", e.getMessage()));
            throw new DAOException(e);
        }
        return Optional.ofNullable(course);
    }

    /**
     * Inserts new course to database
     *
     * @param course - id will be generated by database. Title, duration, start date, category_id nad status_id should be not null.
     * @throws DAOException is wrapper for SQLException
     */
    @Override
    public void add(Course course) throws DAOException, ValidateException {
        try (Connection con = dataSource.getConnection();
             PreparedStatement stmt = con.prepareStatement(INSERT_COURSE)) {
            setStatementFields(course, stmt);
            stmt.executeUpdate();
            log.info(String.format("Course - %s added", course.getTitle()));
        } catch (SQLIntegrityConstraintViolationException e) {
            throw new ValidateException(TITLE_NOT_UNIQUE_MESSAGE);
        } catch (SQLException e) {
            log.error(String.format("Couldn't add new Course - %s. Cause: %s", course.getTitle(), e.getMessage()));
            throw new DAOException();
        }
    }

    /**
     * Updates a course in the database
     *
     * @param course should contain fields to be updated. Title, duration, start date, category_id nad status_id should be not null.
     * @throws DAOException is wrapper for SQLException
     */
    @Override
    public void update(Course course) throws DAOException, ValidateException {
        try (Connection con = dataSource.getConnection();
             PreparedStatement stmt = con.prepareStatement(UPDATE_COURSE)) {
            int k = setStatementFields(course, stmt);
            stmt.setString(++k, String.valueOf(course.getId()));
            stmt.executeUpdate();
            log.info(String.format("Course - %s updated", course.getTitle()));
        } catch (SQLIntegrityConstraintViolationException e) {
            throw new ValidateException(TITLE_NOT_UNIQUE_MESSAGE);
        } catch (SQLException e) {
            log.error(String.format("Couldn't update the Course - %s. Cause: %s", course.getTitle(), e.getMessage()));
            throw new DAOException(e);
        }
    }

    /**
     * Deletes course record in database
     *
     * @param id - value of id field in database
     * @throws DAOException is wrapper for SQLException
     */
    @Override
    public void delete(int id) throws DAOException {
        try (Connection con = dataSource.getConnection();
             PreparedStatement stmt = con.prepareStatement(DELETE_COURSE)) {
            stmt.setInt(1, id);
            stmt.executeUpdate();
            log.info(String.format("Course - %s deleted", id));
        } catch (SQLException e) {
            log.error(String.format("Couldn't delete the Course - %s. Cause: %s", id, e.getMessage()));
            throw new DAOException(e);
        }
    }

    /**
     * Obtains list of all courses from database by parameter in journal
     *
     * @param param -  parameter value
     * @return courses list
     * @throws DAOException is wrapper for SQLException
     */
    @Override
    public Map.Entry<Integer, List<Course>> getByJournal(String param) throws DAOException {
        List<Course> courses = new ArrayList<>();
        int noOfRecords;
        try (Connection con = dataSource.getConnection();
             PreparedStatement stmt = con.prepareStatement(String.format(SELECT_COURSE_BY_JOURNAL, param))) {
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    courses.add(mapRowCourse(rs));
                }
            }
            noOfRecords = setFoundRows(stmt);
        } catch (SQLException e) {
            log.error(String.format("Couldn't get hte Courses. Cause: %s", e.getMessage()));
            throw new DAOException(e);
        }
        return Map.entry(noOfRecords, courses);
    }

    /**
     * Obtains list of all courses from database by parameter
     *
     * @param param -  parameter value
     * @return courses list
     * @throws DAOException is wrapper for SQLException
     */
    @Override
    public Map.Entry<Integer, List<Course>> getAll(String param) throws DAOException {
        List<Course> courses = new ArrayList<>();
        int noOfRecords;
        try (Connection con = dataSource.getConnection();
             PreparedStatement stmt = con.prepareStatement(String.format(SELECT_ALL_COURSES, param))) {
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    courses.add(mapRowCourse(rs));
                }
            }
            noOfRecords = setFoundRows(stmt);
        } catch (SQLException e) {
            log.error(String.format("Couldn't get hte Courses. Cause: %s", e.getMessage()));
            throw new DAOException(e);
        }
        return Map.entry(noOfRecords, courses);
    }

    /**
     * Inserts course and student to journal
     *
     * @param courseId,studentId - must be not null
     * @throws DAOException is wrapper for SQLException
     */
    @Override
    public void insertJournal(int courseId, int studentId) throws DAOException {
        Connection con = null;
        PreparedStatement stmt = null;
        try {
            con = dataSource.getConnection();
            con.setAutoCommit(false);
            stmt = con.prepareStatement(INSERT_JOURNAL);
            int k = 0;
            stmt.setInt(++k, courseId);
            stmt.setInt(++k, studentId);
            stmt.executeUpdate();
            stmt = con.prepareStatement(ADD_NUMBER_STUDENTS_TO_COURSE);
            stmt.setInt(1, courseId);
            stmt.executeUpdate();
            con.commit();
            log.info(String.format("Student %s added to course %s", courseId, studentId));
        } catch (SQLException e) {
            rollback(con);
            log.error(String.format("Student %s didn't add to course %s", courseId, studentId));
            throw new DAOException(e);
        } finally {
            close(stmt);
            close(con);
        }
    }

    /**
     * Updates the student grade for the course
     *
     * @param courseId,studentId,grade - must be not null
     * @throws DAOException is wrapper for SQLException
     */
    @Override
    public void updateJournal(int courseId, int studentId, int grade) throws DAOException {
        try (Connection con = dataSource.getConnection();
             PreparedStatement stmt = con.prepareStatement(UPDATE_JOURNAL)) {
            int k = 0;
            stmt.setInt(++k, grade);
            stmt.setInt(++k, courseId);
            stmt.setInt(++k, studentId);
            stmt.executeUpdate();
            log.info(String.format("Student %s updated to course %s", courseId, studentId));
        } catch (SQLException e) {
            log.error(String.format("Student %s didn't update to course %s", courseId, studentId));
            throw new DAOException(e);
        }
    }

    /**
     * Private methods for class maintenance
     */
    private Course mapRowCourse(ResultSet rs) throws SQLException {
        return Course.builder()
                .id(rs.getInt(COURSE_ID))
                .title(rs.getString(COURSE_TITLE))
                .duration(rs.getInt(COURSE_DURATION))
                .startDate(rs.getDate(COURSE_START_DATE).toLocalDate())
                .amountStudents(rs.getInt(COURSE_AMOUNT_STUDENTS))
                .description(rs.getString(COURSE_DESCRIPTION))
                .status(Status.valueOf(rs.getString(STATUS_TITLE)))
                .category(mapRowCategory(rs))
                .teacher(mapRowTeacher(rs))
                .build();
    }

    private Category mapRowCategory(ResultSet rs) throws SQLException {
        return Category.builder()
                .id(rs.getInt(CATEGORY_ID))
                .title(rs.getString(CATEGORY_TITLE))
                .description(rs.getString(CATEGORY_DESCRIPTION))
                .build();
    }

    private Teacher mapRowTeacher(ResultSet rs) throws SQLException {
        return Teacher.builder()
                .id(rs.getInt(TEACHER_ID))
                .login(rs.getString(USER_LOGIN))
                .password(rs.getString(USER_PASSWORD))
                .name(rs.getString(USER_FIRST_NAME))
                .surname(rs.getString(USER_FAMILY_NAME))
                .email(rs.getString(USER_EMAIL))
                .role(Role.TEACHER)
                .degree(rs.getString(TEACHER_DEGREE))
                .build();
    }

    private int setStatementFields(Course course, PreparedStatement stmt) throws SQLException {
        int k = 0;
        stmt.setString(++k, course.getTitle());
        stmt.setInt(++k, course.getDuration());
        stmt.setDate(++k, Date.valueOf(course.getStartDate()));
        stmt.setString(++k, course.getDescription());
        stmt.setInt(++k, course.getCategory().getId());
        stmt.setInt(++k, course.getStatus().getId());
        stmt.setInt(++k, course.getTeacher().getId());
        return k;
    }


    private Integer setFoundRows(PreparedStatement stmt) throws SQLException {
        ResultSet rs = stmt.executeQuery(SELECT_FOUND_ROWS);
        rs.next();
        return rs.getInt(1);
    }

    private void close(AutoCloseable stmt) throws DAOException {
        if (stmt != null) {
            try {
                stmt.close();
            } catch (Exception e) {
                throw new DAOException(e);
            }
        }
    }

    private void rollback(Connection con) throws DAOException {
        if (con != null) {
            try {
                con.rollback();
            } catch (SQLException e) {
                throw new DAOException(e);
            }
        }
    }
}
